version: '3'

services:
  mongodb:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootnmbp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./nmbpdata:/nmbpdata

volumes:
  mongodb_data: